// <auto-generated />
using System;
using Format.Infra.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Format.Infra.Data.Migrations
{
    [DbContext(typeof(FormatDbContext))]
    partial class FormatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Format.Domain.Models.Documento", b =>
                {
                    b.Property<int>("IdDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocumento"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdTipoDocumento")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("IdDocumento");

                    b.HasIndex("IdTipoDocumento");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Documento");
                });

            modelBuilder.Entity("Format.Domain.Models.Referencias", b =>
                {
                    b.Property<int>("IdReferencias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReferencias"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDocumento")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("IdReferencias");

                    b.HasIndex("IdDocumento");

                    b.ToTable("Referencias");
                });

            modelBuilder.Entity("Format.Domain.Models.Secoes", b =>
                {
                    b.Property<int>("IdSecoes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSecoes"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDocumento")
                        .HasColumnType("int");

                    b.Property<int?>("IdPai")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("IdSecoes");

                    b.HasIndex("IdDocumento");

                    b.HasIndex("IdPai");

                    b.ToTable("Secoes");
                });

            modelBuilder.Entity("Format.Domain.Models.SecoesConteudo", b =>
                {
                    b.Property<int>("IdSecoesConteudo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSecoesConteudo"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdSecoes")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("IdSecoesConteudo");

                    b.HasIndex("IdSecoes");

                    b.ToTable("SecoesConteudo");
                });

            modelBuilder.Entity("Format.Domain.Models.TipoDocumento", b =>
                {
                    b.Property<int>("IdTipoDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoDocumento"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("IdTipoDocumento");

                    b.ToTable("TipoDocumento");
                });

            modelBuilder.Entity("Format.Domain.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Format.Domain.Models.Documento", b =>
                {
                    b.HasOne("Format.Domain.Models.TipoDocumento", "TipoDocumento")
                        .WithMany("Documentos")
                        .HasForeignKey("IdTipoDocumento")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Format.Domain.Models.Usuario", "Usuario")
                        .WithMany("Documentos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoDocumento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Format.Domain.Models.Referencias", b =>
                {
                    b.HasOne("Format.Domain.Models.Documento", "Documento")
                        .WithMany("Referencias")
                        .HasForeignKey("IdDocumento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("Format.Domain.Models.Secoes", b =>
                {
                    b.HasOne("Format.Domain.Models.Documento", "Documento")
                        .WithMany("Secoes")
                        .HasForeignKey("IdDocumento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Format.Domain.Models.Secoes", "SecaoPai")
                        .WithMany("SecoesFilhas")
                        .HasForeignKey("IdPai")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Documento");

                    b.Navigation("SecaoPai");
                });

            modelBuilder.Entity("Format.Domain.Models.SecoesConteudo", b =>
                {
                    b.HasOne("Format.Domain.Models.Secoes", "Secoes")
                        .WithMany("SecoesConteudos")
                        .HasForeignKey("IdSecoes")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Secoes");
                });

            modelBuilder.Entity("Format.Domain.Models.Documento", b =>
                {
                    b.Navigation("Referencias");

                    b.Navigation("Secoes");
                });

            modelBuilder.Entity("Format.Domain.Models.Secoes", b =>
                {
                    b.Navigation("SecoesConteudos");

                    b.Navigation("SecoesFilhas");
                });

            modelBuilder.Entity("Format.Domain.Models.TipoDocumento", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("Format.Domain.Models.Usuario", b =>
                {
                    b.Navigation("Documentos");
                });
#pragma warning restore 612, 618
        }
    }
}
